Use plymouth in Update and Rescue modes
Also:
- change order of S97upgrade tasks, leaving resize for last because of the need to update kernel.
- make sure /etc/init.d script are executable.
- added needed find command.

diff --git a/board/fsoverlay/etc/init.d/S97update b/board/fsoverlay/etc/init.d/S97update
--- a/board/fsoverlay/etc/init.d/S97update
+++ b/board/fsoverlay/etc/init.d/S97update
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-# only at start AND if triggered
-if [ "$1" != "start" ] || [ ! -f /boot/REG_UPDATE ]
+# Quit if is not start OR rescue mode is requested OR no update trigger exists
+if [ "$1" != "start" ] || [ -f /boot/REG_RESCUE ] || [ ! -f /boot/REG_UPDATE ]
 then
     exit 0
 fi
@@ -19,6 +19,7 @@ function display_error()
 {
     /usr/bin/plymouth display-message --text="ERROR! Please check the log at: /boot/rescue.log"
     cp --backup=simple "$LOG" /boot/
+    touch /boot/REG_RESCUE
     exit 1
 }
 
@@ -86,7 +87,7 @@ function extractupgradefiles()
     # Exclude batocera-boot.conf to avoid losing user settings and restoring triggers
     # Also exclude files already updated
     # tar --no-same-owner is needed because fat partition does not support owner attributes
-    if ! tar -C /boot/ --no-same-owner --exclude='batocera-boot.conf' --exclude='boot/firmware.update' --exclude='boot/initrd.lz4' --exclude='boot/linux' --exclude='boot/modules.update' --exclude='boot/rescue.update' --zstd -xf "${SHAREMOUNT}/system/upgrade/boot-${board}.tar.zst"
+    if ! tar -C /boot/ --no-same-owner --exclude='batocera-boot.conf' --exclude='boot/config.txt' --zstd -xf "${SHAREMOUNT}/system/upgrade/boot-${board}.tar.zst"
     then
         echo "Error extracting files from ${SHAREMOUNT}/system/upgrade/boot-${board}.tar.zst"
         exit 1
@@ -99,23 +100,25 @@ TOTALSTEPS=0    # To help with progress bar
 CURRENTSTEP=0   # use multiples of 100 (100, 200, 300, etc., instead of 1, 2, 3, etc.)
 TASKS=0         # 1111
                 # ^^^^
-                # ||||_ Finish upgrade
+                # ||||_ Resize (expand) share_internal partition
                 # |||__ Format share_internal partition
                 # ||___ Change UUID of boot partition
-                # |____ Resize (expand) share_internal partition
+                # |____ Finish upgrade
 
 if grep -qE '^[ ]*autoresize[ ]*=[ ]*true[ ]*$' "${BOOTCONF}"; then
     ((TOTALSTEPS+=10))
-    ((TASKS+=1000))
+    ((TASKS+=1))
 fi
-if grep -qE '^[ ]*newbootuuid[ ]*=[ ]*true[ ]*$' "${BOOTCONF}"; then
-    ((TOTALSTEPS+=4))
-    ((TASKS+=100))
-fi
+
 FORMAT_INTERNAL_TYPE=$(grep -m 1 -E '^[ ]*format-internal[ ]*=.*$' "${BOOTCONF}" | sed -e "s+^[ ]*format-internal[ ]*=[ ]*\(.*\)[ ]*$+\1+")
 if [ -n "$FORMAT_INTERNAL_TYPE" ]; then
     ((TOTALSTEPS+=6))
     ((TASKS+=10))
+fi
+
+if grep -qE '^[ ]*newbootuuid[ ]*=[ ]*true[ ]*$' "${BOOTCONF}"; then
+    ((TOTALSTEPS+=4))
+    ((TASKS+=100))
 fi
 
 # Search for upgrade file to finish upgrading REG-linux
@@ -126,68 +129,46 @@ SHAREMOUNT=$(grep -m 1 -E "^$SHAREPART " /proc/mounts | awk '{print $2}')
 board=$(cat /boot/boot/batocera.board)
 if [ -f "${SHAREMOUNT}/system/upgrade/boot-${board}.tar.zst" ]; then
     ((TOTALSTEPS+=6))
-    ((TASKS+=1))
+    ((TASKS+=1000))
 fi
 
 ### Tasks list done.
 [ "$TASKS" -eq 0 ] && exit 0    # Greater than 0 if there is something to do
 
-# only when resizing of share_internal is wanted (usually first boot only)
+# finish upgrading REG-linux if upgrade file found
 if [ "$TASKS" -ge 1000 ]; then
 
-    # /userdata partition
-    PARTNUM=$(batocera-part "share_internal_num")
-    echo "Partition name: $SHAREPART & number: $PARTNUM" >> "$LOG"
+    # Mount share_internal again if needed
+    SHAREMOUNT=$(grep -m 1 -E "^$SHAREPART " /proc/mounts | awk '{print $2}')
+    [ -z "$SHAREMOUNT" ] && mountshareinternal
 
-    # boot disk
-    DISK=$(batocera-part prefix "${SHAREPART}")
-    echo "Disk = $DISK" >> "$LOG"
+    echo "Found update: ${SHAREMOUNT}/system/upgrade/boot-${board}.tar.zst" >> "$LOG"
 
-    # only for ext4
-    PARTTYPE=$(blkid -o value -s TYPE "${SHAREPART}")
-    echo "Partition type = ${PARTTYPE}" >> "$LOG"
-    if [ "${PARTTYPE}" = "ext4" ]; then
-
-        # umount share_internal
-        umount -A "$SHAREPART"
-        # partition table
-        TABLETYPE=$(blkid -o value -s PTTYPE "${DISK}")
-        echo "Disk partition table type = $TABLETYPE" >> "$LOG"
-
-        # if GPT, move backup data structures to the end of the disk
-        ((CURRENTSTEP+=50))
-        if [ "${TABLETYPE}" = "gpt" ]; then
-            echo "Moving 2nd GPT table to the end of the disk" >> "$LOG"
-            cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "sgdisk -e ${DISK}" "Aligning GPT table"
-        fi
-
-        # resize the partition
-        echo "Resizing the partition to 100%" >> "$LOG"
-        ((CURRENTSTEP+=150))
-        cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "parted -s -m -f ${DISK} resizepart ${PARTNUM} 100%" "Resizing partition"
-
-        # update the kernel
-        echo "Updating the kernel" >> "$LOG"
-        ((CURRENTSTEP+=100))
-        cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "partprobe ${DISK}" "Informing the Kernel"
-
-        # check & resize the ext4 file system
-        echo "Checking ext4 file system" >> "$LOG"
-        ((CURRENTSTEP+=100))
-        cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "e2fsck -f -p ${SHAREPART}" "Checking /userdata integrity"
-
-        echo "Expanding ext4 the file system" >> "$LOG"
-        ((CURRENTSTEP+=200))
-        cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "resize2fs ${SHAREPART}" "Expanding the file system"
-
-        echo "Checking ext4 file system" >> "$LOG"
-        ((CURRENTSTEP+=250))
-        cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "e2fsck -f -p ${SHAREPART}" "Checking ext4 file system"
+    # First get the list of available files to see if it includes reglinux
+    if tar --zstd -tf "${SHAREMOUNT}/system/upgrade/boot-${board}.tar.zst" | grep 'boot/reglinux'
+    then
+    	# Delete previous reglinux because we need the space
+		((CURRENTSTEP+=50))
+		cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "rm -f /boot/boot/reglinux" "Deleting previous REG-linux OS"
     fi
-    # remove the trigger
-    ((TASKS-=1000))
+
     ((CURRENTSTEP+=100))
-    cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "remove_trigger autoresize" "Removing trigger"
+    cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "extractupgradefiles" "Extracting upgrade files"
+
+    # Fix uuid
+    ((CURRENTSTEP+=400))
+    BOOTPART=$(/usr/bin/batocera-part boot)
+    NEWUUID=$(blkid -o value -s UUID "$BOOTPART")
+    if [ -n "$NEWUUID" ]
+    then
+        echo "Updating boot files with boot partition UUID" >> "$LOG"
+        cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "replaceuuid" "Updating UUID in boot files"
+    else
+        echo "Error getting UUID of boot partition" >> "$LOG"
+        display_error
+    fi
+    mv "${SHAREMOUNT}/system/upgrade/boot-${board}.tar.zst" "${SHAREMOUNT}/system/upgrade/already-installed-boot-${board}.tar.zst"
+    ((TASKS-=1000))
 fi
 
 # only when random UUID for boot partition is wanted (usually first boot only)
@@ -243,32 +224,64 @@ if [ "$TASKS" -ge 10 ]; then
     cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "remove_trigger format-internal" "Removing trigger"
 fi
 
-# finish upgrading REG-linux if upgrade file found
+# only when resizing of share_internal is wanted (usually first boot only)
 if [ "$TASKS" -ge 1 ]; then
 
-    # Mount share_internal again if needed
-    SHAREMOUNT=$(grep -m 1 -E "^$SHAREPART " /proc/mounts | awk '{print $2}')
-    [ -z "$SHAREMOUNT" ] && mountshareinternal
+    # /userdata partition
+    PARTNUM=$(batocera-part "share_internal_num")
+    echo "Partition name: $SHAREPART & number: $PARTNUM" >> "$LOG"
 
-    echo "Found update: ${SHAREMOUNT}/system/upgrade/boot-${board}.tar.zst" >> "$LOG"
-    ((CURRENTSTEP+=50))
-    cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "rm -f /boot/boot/reglinux" "Deleting previous REG-linux OS"
+    # boot disk
+    DISK=$(batocera-part prefix "${SHAREPART}")
+    echo "Disk = $DISK" >> "$LOG"
 
-    ((CURRENTSTEP+=100))
-    cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "extractupgradefiles" "Extracting upgrade files"
+    # only for ext4
+    PARTTYPE=$(blkid -o value -s TYPE "${SHAREPART}")
+    echo "Partition type = ${PARTTYPE}" >> "$LOG"
+    if [ "${PARTTYPE}" = "ext4" ]; then
 
-    # Fix uuid
-    ((CURRENTSTEP+=400))
-    BOOTPART=$(/usr/bin/batocera-part boot)
-    NEWUUID=$(blkid -o value -s UUID "$BOOTPART")
-    if [ -n "$NEWUUID" ]
-    then
-        echo "Updating boot files with boot partition UUID" >> "$LOG"
-        cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "replaceuuid" "Updating UUID in boot files"
-    else
-        echo "Error getting UUID of boot partition" >> "$LOG"
-        display_error
+        # umount share_internal
+        while grep -m 1 -E "^$SHAREPART " /proc/mounts; do
+            umount "$SHAREPART"
+            sleep 1
+        done
+        # partition table
+        TABLETYPE=$(blkid -o value -s PTTYPE "${DISK}")
+        echo "Disk partition table type = $TABLETYPE" >> "$LOG"
+
+        # if GPT, move backup data structures to the end of the disk
+        ((CURRENTSTEP+=50))
+        if [ "${TABLETYPE}" = "gpt" ]; then
+            echo "Moving 2nd GPT table to the end of the disk" >> "$LOG"
+            cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "sgdisk -e ${DISK}" "Aligning GPT table"
+        fi
+
+        # resize the partition
+        echo "Resizing the partition to 100%" >> "$LOG"
+        ((CURRENTSTEP+=150))
+        cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "parted -s -m -f ${DISK} resizepart ${PARTNUM} 100%" "Resizing partition"
+
+        # update the kernel
+        echo "Updating the kernel" >> "$LOG"
+        ((CURRENTSTEP+=100))
+        cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "partprobe ${DISK}" "Informing the Kernel"
+
+        # check & resize the ext4 file system
+        echo "Checking ext4 file system" >> "$LOG"
+        ((CURRENTSTEP+=200))
+        cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "e2fsck -f -p ${SHAREPART}" "Checking /userdata integrity"
+
+        echo "Expanding ext4 the file system" >> "$LOG"
+        ((CURRENTSTEP+=250))
+        cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "resize2fs ${SHAREPART}" "Expanding the file system"
+
+        echo "Checking ext4 file system" >> "$LOG"
+        ((CURRENTSTEP+=200))
+        cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "e2fsck -f -p ${SHAREPART}" "Checking ext4 file system"
     fi
+    # remove the trigger
+    ((CURRENTSTEP+=100))
+    cmdoutput $((CURRENTSTEP / TOTALSTEPS)) "remove_trigger autoresize" "Removing trigger"
 fi
 
 # finally disk sync
